In [1]:
import numpy as np

Задание_1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. 
Первый столбец должен содержать числа 1, 2, 3, 3, 1, 
а второй - числа 6, 8, 11, 10, 7. 
Будем считать, что каждый столбец - это признак, а строка - наблюдение. 
Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. 
Результат запишите в массив mean_a, в нем должно быть 2 элемента

In [2]:
F = np.array([[1, 2, 3, 3, 1],
              [6, 8, 11, 10, 7]])
A = F.T
A


array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
print("Средние значения строк (наблюдений): {}".format(A.mean(axis=1)))

print("Средние значения столбцов (признака): {}".format(A.mean(axis=0)))

Средние значения строк (наблюдений): [3.5 5.  7.  6.5 4. ]
Средние значения столбцов (признака): [2.  8.4]


In [7]:
mean_a = A.mean(axis=0)
print("Ответ: средние среднее значение по каждому признаку", mean_a)


Ответ: средние среднее значение по каждому признаку [2.  8.4]


Задание_2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, 
содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. 
Получившийся массив должен иметь размер 5x2.

In [10]:
a_centered = A - mean_a
print("Ответ: Концепция broadcasting даст результат, a_centered =")
a_centered

Ответ: Концепция broadcasting даст результат, a_centered =


array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание_3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. 
Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [11]:
Nd = A.shape
N = Nd[0]
N


5

In [13]:
a_centered_1 = a_centered.T[0]
a_centered_2 = a_centered.T[1]
a_centered_1, a_centered_2

(array([-1.,  0.,  1.,  1., -1.]), array([-2.4, -0.4,  2.6,  1.6, -1.4]))

In [16]:
ap= np.dot(a_centered_1, a_centered_2)
a_centered_sp = ap / (N-1)
print("скалярное произведение столбцов массива a_centered", ap)
print("результат деления a_centered_sp на N-1, a_centered_sp =", a_centered_sp)

скалярное произведение столбцов массива a_centered 8.0
результат деления a_centered_sp на N-1, a_centered_sp = 2.0


Задание_4** 
Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. 
В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому 
полученная нами величина является несмещенной оценкой ковариации.
Подробнее узнать о ковариации можно здесь:
Выборочная ковариация и выборочная дисперсия — Студопедия
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. 
В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [21]:
A_0= F[0]
A_1= F[1]
A_0, A_1

(array([1, 2, 3, 3, 1]), array([ 6,  8, 11, 10,  7]))

In [22]:
covariance = np.cov(A_0, A_1)[0][1]
print(covariance)

2.0


In [38]:
#ковариация этих двух величин: без использования специальных функций 
m_0 = np.mean(A_0) 
m_1 = np.mean(A_1) 
cov = ((A_0 - m_0) * (A_1 - m_1)).sum() / (A_0.shape[0] - 1)
cov

2.0